server:
  port : 8888

eureka:
  instance:
    #hostname: 47.98.60.240
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000

spring:
  application:
    name: eurekaserver
