server:
  port: 8081
spring:
  application:
    name: swaggerserver
eureka:
  client:
    serviceUrl:
      #defaultZone: http://47.98.60.240:8888/eureka/
      defaultZone: http://localhost:8888/eureka/
feign:
  hystrix:
    enabled: true

